const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
const GET_PATIENT_DETAIL = 'GET_PATIENT_DETAIL';
const SEND_ALERT = 'SEND_ALERT';
const SET_LEFT_SIDE = 'SET_LEFT_SIDE';
const SET_RIGHT_SIDE = 'SET_RIGHT_SIDE';

export { 
  CREATE_ACCOUNT,
  GET_PATIENT_DETAIL,
  SEND_ALERT,
  SET_LEFT_SIDE,
  SET_RIGHT_SIDE
};