const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
const GET_PATIENT_DETAIL = 'GET_PATIENT_DETAIL';
const GET_PATIENT_LIST = 'GET_PATIENT_LIST';
const SEND_ALERT = 'SEND_ALERT';
const SET_LEFT_SIDE = 'SET_LEFT_SIDE';
const SET_RIGHT_SIDE = 'SET_RIGHT_SIDE';
const SHOW_FLAGGED = 'SHOW_FLAGGED';
const TOGGLE_FLAG = 'TOGGLE_FLAG';
const GET_MESSAGES = 'GET_MESSAGES';
const SEND_MESSAGE = 'SEND_MESSAGE';

export { 
  CREATE_ACCOUNT,
  GET_PATIENT_DETAIL,
  GET_PATIENT_LIST,
  SEND_ALERT,
  SET_LEFT_SIDE,
  SET_RIGHT_SIDE,
  SHOW_FLAGGED,
  TOGGLE_FLAG,
  GET_MESSAGES,
  SEND_MESSAGE,
};
